//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.Consciencia.Pruebas.NoticiaWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoNoticia", Namespace="")]
    [System.SerializableAttribute()]
    public partial class CatalogoNoticia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdNoticiaField;
        
        private string MedioField;
        
        private System.DateTime FechaHoraField;
        
        private string TituloField;
        
        private string ContenidoField;
        
        private string SituacionRegistroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdNoticia {
            get {
                return this.IdNoticiaField;
            }
            set {
                if ((this.IdNoticiaField.Equals(value) != true)) {
                    this.IdNoticiaField = value;
                    this.RaisePropertyChanged("IdNoticia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Medio {
            get {
                return this.MedioField;
            }
            set {
                if ((object.ReferenceEquals(this.MedioField, value) != true)) {
                    this.MedioField = value;
                    this.RaisePropertyChanged("Medio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime FechaHora {
            get {
                return this.FechaHoraField;
            }
            set {
                if ((this.FechaHoraField.Equals(value) != true)) {
                    this.FechaHoraField = value;
                    this.RaisePropertyChanged("FechaHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string Contenido {
            get {
                return this.ContenidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContenidoField, value) != true)) {
                    this.ContenidoField = value;
                    this.RaisePropertyChanged("Contenido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string SituacionRegistro {
            get {
                return this.SituacionRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.SituacionRegistroField, value) != true)) {
                    this.SituacionRegistroField = value;
                    this.RaisePropertyChanged("SituacionRegistro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NoticiaWS.INoticia")]
    public interface INoticia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoticia/GrabarNoticia", ReplyAction="http://tempuri.org/INoticia/GrabarNoticiaResponse")]
        UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia[] GrabarNoticia(UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia[] Noticia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoticia/GrabarNoticia", ReplyAction="http://tempuri.org/INoticia/GrabarNoticiaResponse")]
        System.Threading.Tasks.Task<UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia[]> GrabarNoticiaAsync(UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia[] Noticia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoticia/ListarCatalogoNoticiaPorId", ReplyAction="http://tempuri.org/INoticia/ListarCatalogoNoticiaPorIdResponse")]
        UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia ListarCatalogoNoticiaPorId(int intIdNoticia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoticia/ListarCatalogoNoticiaPorId", ReplyAction="http://tempuri.org/INoticia/ListarCatalogoNoticiaPorIdResponse")]
        System.Threading.Tasks.Task<UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia> ListarCatalogoNoticiaPorIdAsync(int intIdNoticia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoticia/ListarCatalogoNoticia", ReplyAction="http://tempuri.org/INoticia/ListarCatalogoNoticiaResponse")]
        UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia[] ListarCatalogoNoticia(UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia ent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoticia/ListarCatalogoNoticia", ReplyAction="http://tempuri.org/INoticia/ListarCatalogoNoticiaResponse")]
        System.Threading.Tasks.Task<UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia[]> ListarCatalogoNoticiaAsync(UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia ent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoticia/CambiarSituacionCatalogoNoticia", ReplyAction="http://tempuri.org/INoticia/CambiarSituacionCatalogoNoticiaResponse")]
        UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia CambiarSituacionCatalogoNoticia(int intIdNoticia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoticia/CambiarSituacionCatalogoNoticia", ReplyAction="http://tempuri.org/INoticia/CambiarSituacionCatalogoNoticiaResponse")]
        System.Threading.Tasks.Task<UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia> CambiarSituacionCatalogoNoticiaAsync(int intIdNoticia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INoticiaChannel : UPC.Consciencia.Pruebas.NoticiaWS.INoticia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NoticiaClient : System.ServiceModel.ClientBase<UPC.Consciencia.Pruebas.NoticiaWS.INoticia>, UPC.Consciencia.Pruebas.NoticiaWS.INoticia {
        
        public NoticiaClient() {
        }
        
        public NoticiaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NoticiaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoticiaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoticiaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia[] GrabarNoticia(UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia[] Noticia) {
            return base.Channel.GrabarNoticia(Noticia);
        }
        
        public System.Threading.Tasks.Task<UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia[]> GrabarNoticiaAsync(UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia[] Noticia) {
            return base.Channel.GrabarNoticiaAsync(Noticia);
        }
        
        public UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia ListarCatalogoNoticiaPorId(int intIdNoticia) {
            return base.Channel.ListarCatalogoNoticiaPorId(intIdNoticia);
        }
        
        public System.Threading.Tasks.Task<UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia> ListarCatalogoNoticiaPorIdAsync(int intIdNoticia) {
            return base.Channel.ListarCatalogoNoticiaPorIdAsync(intIdNoticia);
        }
        
        public UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia[] ListarCatalogoNoticia(UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia ent) {
            return base.Channel.ListarCatalogoNoticia(ent);
        }
        
        public System.Threading.Tasks.Task<UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia[]> ListarCatalogoNoticiaAsync(UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia ent) {
            return base.Channel.ListarCatalogoNoticiaAsync(ent);
        }
        
        public UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia CambiarSituacionCatalogoNoticia(int intIdNoticia) {
            return base.Channel.CambiarSituacionCatalogoNoticia(intIdNoticia);
        }
        
        public System.Threading.Tasks.Task<UPC.Consciencia.Pruebas.NoticiaWS.CatalogoNoticia> CambiarSituacionCatalogoNoticiaAsync(int intIdNoticia) {
            return base.Channel.CambiarSituacionCatalogoNoticiaAsync(intIdNoticia);
        }
    }
}
